services:
  ollama:
    image: ollama/ollama
    container_name: ollama_app
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - ./ollama:/root/.ollama
      - ./customize_model:/root/customize_model
      - ./run.sh:/root/run.sh
    restart: always
    networks:
      - lahatrad_network

networks:
  lahatrad_network:
